language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script: 
  - yarn test
notifications:
  slack: ---
  email: 
    recipients: 
      - fermartorr01@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 4d3d8fe4-8457-417a-96a0-992c0f8d8b01
  app: platzi-store-backend-fermin
  on:
    repo: FerminMartin/platzi-store-backend