lenguage: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js: 
  - '12'

git:
  depth: 3

script:
  - yarn test

deploy:
  provide: heroku
  skip_cleanup: true
  keep_history: true
  api_key: 3fe69f8c-3371-40f2-9f6e-90b27db5bfc5
  app: travis-test-backend
  on:
    repo: mau02ro/platzi-store-backend
