language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack: zvelez:Wl8pygh5ZKstLllFcWwLK3uQ
  email: 
    recipients:
      - zvelez@gmail.com
    on_success: always
    on_faliure: always
deploy: 
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api-key: 2cfe2d09-73bc-4692-b004-f1c7a678002e
  app: curso-cicd-backend
  on:
    repo: zvelez/platzi-store-backend

